version: '2'
services:
    app:
        # image: koda/docker-knowledge:japanese
        build: ./docker_knowledge
        volumes:
            - ./volumes/knowledge:/root/.knowledge
            # - ./backup/volumes/220805/knowledge:/root/.knowledge # バックアップ
        ports:
            - 48080:8080
        restart: always
        depends_on:
            - "db"
    db:
        image: postgres:9
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_DB=knowledge_production
        volumes:
            #- ./volumes/initdb:/docker-entrypoint-initdb.d
            # - ./volumes/postgres/data:/var/lib/postgresql/data
            - type: bind
              source: ./volumes/postgres/data
              target: /var/lib/postgresql/data
        restart: always